<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "imagecredits14v"
 *
 * Auto generated by Extension Builder 2019-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'ImageCredits14v',
    'description' => 'Provides an overview of all used images with copyright information in the frontend and a backend module for managing copyright details.',
    'category' => 'plugin',
    'author' => 'Oliver Busch',
    'author_email' => 'ob@14v.de',
    'author_company' => 'one4vision GmbH',
    'clearCacheOnLoad' => true,
    'state' => 'stable',
    'version' => '12.3.1',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
            'filemetadata' => '12.4.0-12.4.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
